// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAacsz43gy4muGVGyJ_h1Lh9iG2DTEr8ao',
    appId: '1:981273248425:web:bccbb2608bdf2231945fb8',
    messagingSenderId: '981273248425',
    projectId: 'laudo-ez',
    authDomain: 'laudo-ez.firebaseapp.com',
    storageBucket: 'laudo-ez.appspot.com',
    measurementId: 'G-SZTMPB8TCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjhVkIwD3kCP9vuuwl57N0loUpR6h54As',
    appId: '1:981273248425:android:904ad715e65693b6945fb8',
    messagingSenderId: '981273248425',
    projectId: 'laudo-ez',
    storageBucket: 'laudo-ez.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAacsz43gy4muGVGyJ_h1Lh9iG2DTEr8ao',
    appId: '1:981273248425:web:a6803fd56267f592945fb8',
    messagingSenderId: '981273248425',
    projectId: 'laudo-ez',
    authDomain: 'laudo-ez.firebaseapp.com',
    storageBucket: 'laudo-ez.appspot.com',
    measurementId: 'G-KWZ8Z8QD6T',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAacsz43gy4muGVGyJ_h1Lh9iG2DTEr8ao',
    appId: '1:981273248425:web:a03907e7c4dd9e9b945fb8',
    messagingSenderId: '981273248425',
    projectId: 'laudo-ez',
    authDomain: 'laudo-ez.firebaseapp.com',
    storageBucket: 'laudo-ez.appspot.com',
    measurementId: 'G-Q7V9C6Q1GG',
  );
}
